/*001*/
SELECT CITY, REGION, SALES
FROM OFFICES
ORDER BY REGION, CITY;

/*002*/
SELECT CITY, REGION, SALES
FROM OFFICES
ORDER BY REGION DESC;

/*003*/
SELECT CITY, REGION, SALES
FROM OFFICES
ORDER BY (REGION - TARGET) DESC;

/*004*/
SELECT CITY, (SALES - TARGET)
FROM OFFICES
ORDER BY REGION ASC, 3 DESC;
