/*034*/
SELECT CITY, REGION, SALES
FROM OFFICES
ORDER BY REGION, CITY;

/*035*/
SELECT CITY, REGION, SALES
FROM OFFICES
ORDER BY REGION DESC;

/*036*/
SELECT CITY, REGION, SALES
FROM OFFICES
ORDER BY (REGION - TARGET) DESC;

/*037*/
SELECT CITY, (SALES - TARGET)
FROM OFFICES
ORDER BY REGION ASC, 3 DESC;
