/*038*/
SELECT MRF_ID, PRODUCT_ID
FROM PRODUCTS
WHERE PRICE > 2000.00
  UNION
SELECT DISTINCT MRF, PRODUCT
FROM ORDERS
WHERE AMOUN > 3000.00;

/*039*/
SELECT MRF_ID, PRODUCT_ID
FROM PRODUCTS
WHERE PRICE > 2000.00
  UNION ALL
SELECT DISTINCT MRF, PRODUCT
FROM ORDERS
WHERE AMOUN > 3000.00;

/*040*/
SELECT *
FROM A
  UNION (SELECT *
         FROM B
          UNION
         SELECT *
         FROM C);