/*014*/
SELECT CITY, SALES, TARGET
FROM OFFICES
WHERE SALEC > TARGET;

/*015*/
SELECT NAME, SALES, QUOTA
FROM SALESREPS
WHERE EMPL_NUM = 105;

/*016*/
SELECT NAME, SALES, QUOTA
FROM SALESREPS
WHERE MANAGER = 105;

/*017*/
SELECT NAME
FROM SALESREPS
WHERE HIRE_DATE < '2018-01-01';

/*018*/
SELECT CITY, SALES, TARGET
FROM OFFICES
WHERE SALES < (.8 * TARGET);

/*019*/
SELECT CITY, MGR
FROM OFFICES
WHERE MGR <> 108;

/*020*/
SELECT COMPANY, CREDIT_LIMIT
FROM CUSTOMERS
WHERE CUST_NUM = 2017;

/*021*/
SELECT ORDER_NUM, ORDER_DATE, MFR, PRODUCT, AMOUNT
FROM ORDERS
WHERE ORDER_DATE BETWEEN '2017-10-01' AND '2007-12-31';

/*022*/
SELECT ORDER_NUM, AMOUNT
FROM ORDERS
WHERE AMOUNT BETWEEN 20000.00 AND 29999.99;

/*023*/
SELECT NAME, SALES, QUOTA
FROM SALESREPS
WHERE SALES NOT BETWEEN (.8 * QOUTA) AND (1.2 * QOUTA);

/*024*/
SELECT NAME, QUOTA, SALES
FROM  SALESREPS
WHERE REP_OFFICE IN (11, 13, 22);

/*025*/
SELECT ORDER_NUM, ORDER_DATE, AMOUNT
FROM ORDERS
WHERE ORDER_DATE IN ('2008-01-01','2018-01-01');

/*026*/
SELECT COMPANY, CREDIT_LIMIT
FROM CUSTOMERS
WHERE COMPANY = 'Smithson Corp.';

/*027*/
SELECT COMPANY, CREDIT_LIMIT
FROM CUSTOMERS
WHERE COMPANY LIKE 'Smithson Corp.';

/*028*/
SELECT COMPANY, CREDIT_LIMIT
FROM CUSTOMERS
WHERE COMPANY LIKE 'Smith_n %';

/*029*/
SELECT COMPANY, CREDIT_LIMIT
FROM CUSTOMERS
WHERE COMPANY NOT LIKE 'Smith_n %';

/*030*/
SELECT ORDER_NUM, PRODUCT
FROM ORDERS
WHERE PRODUCT LIKE 'A$%BC&' ESCAPE '$';

/*031*/
SELECT NAME
FROM SALESREPS
WHERE REP_OFFICE IS NULL;

/*031*/
SELECT NAME
FROM SALESREPS
WHERE REP_OFFICE IS NOT NULL;

/*032*/
SELECT NAME, QUOTA, SALES
FROM SALESREPS
WHERE SALES < QUOTA
  AND SALES < 300000.00;

/*033*/
SELECT NAME
FROM SALESREPS
WHERE (REP_OFFICE IN (22, 11, 12))
  OR (MANAGER IS NULL AND HIRE_DATE >= '2018-01-01')
  OR (SALES > QOUTA AND NOT SALES > 600000.00);