/*001*/
DELETE FROM SALESREPS
WHERE NAME = 'HENRY';

/*002*/
DELETE FROM ORDERS
WHERE CUST = 2126;

/*003*/
DELETE FROM CUSTOMER
WHERE CUST_REP IN (105, 109, 101);

/*004*/
DELETE FROM SALESREPS
WHERE HIRE_DATE < '2010-01-01'
  AND QUOTA IS NULL;

/*005*/
DELETE FROM ORDERS;

/*006*/
DELETE FROM ORDERS
WHERE REP = (SELECT EMPL_NUM
             FROM SALESREPS
             WHERE NAME = 'SUE SMITH');

/*007*/
DELETE FROM CUSTOMERS
WHERE CUST_REP IN (SELECT EMPL_NUM
                   FROM SALESREPS
                   WHERE SALES < (.8 * QUOTA));

/*008*/
DELETE FROM CUSTOMERS
WHERE NOT EXISTS(SELECT * FROM ORDERS
                 WHERE CUST = CUST_NUM
                  AND REDER_DATE > '2007-01-01');

