/*001*/
INSERT INTO SALESREPS (NAME, AGE, EMPL_NUM, SALES, TITLE, HIRE_DATE, REP_OFFICE)
    VALUES ('HENRY', 36, 111, 0.00, 'SALES MGR', '2017-01-01', 13);

/*002*/
INSERT INTO SALESREPS (NAME, AGE, EMPL_NUM, SALES, TITLE, HIRE_DATE, REP_OFFICE)
VALUES ('HENRY', 36, 111, 0.00, NULL, NULL, 13);

/*003*/
INSERT INTO OLDORDERS (OREDR_NUM, ORDER_DATE, AMOUNT)
    SELECT OREDR_NUM, ORDER_DATE, AMOUNT
    FROM ORDERS WHERE ORDER_DATE < '2017-01-01';

/*004*/
INSERT INTO BIGORDERS (AMOUNT, COMPANY, NAME, PERF, PRODUCT, MFR, QTY)
    SELECT AMOUNT, COMPANY, NAME, PERF, PRODUCT, MFR, QTY
    FROM ORDERS, CUSTOMERS, SALESREPS
    WHERE CUST = CUST_NUM
      AND REP = EMOL_NUM
      AND AMOUNT > 15000.00;

