/*
SUM(),
AVG(),
MIN(),
MAX(),
COUNT(),
COUNT(*)
*/

/*001*/
SELECT AVG(QUOTA), AVG(SALES)
FROM SALESREPS;

/*002*/
SELECT AVG(100 * (SALES/QUOTA))
FROM SALESREPS;

/*003*/
SELECT SUM(QUOTA), SUM(SALES)
FROM SALESREPS;

/*004*/
SELECT SUM(AMOUNT)
FROM ORDERS, SALESREPS
WHERE NAME = 'Bill Adams'
  AND REP = EMPL_NUM;

/*005*/
SELECT AVG(PRICE)
FROM PRODUCTS
WHERE MFR_ID = 'ACI';

/*006*/
SELECT MIN(QUOTA), MAX(QUOTA)
FROM SALESREPS;

/*007*/
SELECT MAX(100 * (SALES/QUOTA))
FROM SALESREPS;

/*008*/
SELECT COUNT(CUST_NUM)
FROM CUSTOMERS;

/*009*/
SELECT COUNT(*)
FROM ORDERS
WHERE AMOUNT > 25000.00;

/*010*/
SELECT AVG(AMOUNT), SUM(AMOUNT), (100 * AVG(AMOUNT/CREDIT_LIMIT)), (100 * AVG(AMOUNT/QUOTA))
FROM ORDERS, CUSTOMERS, SALESREPS
WHERE CUST = CUST_NUM
  AND REP = EMPL_NUM;

/*011*/
SELECT COUNT(*), COUNT(SALES), COUNT(QUOTA)
FROM SALESREPS;

/*012*/
SELECT COUNT(DISTINCT TITLE)
FROM SALESREPS;

