/*001*/
CREATE VIEW EASTREPS AS
  SELECT *
  FROM SALESREPS
  WHERE REP_OFFICE IN (11,12,13);

/*002*/
CREATE VIEW SUEORDERS AS
  SELECT *
  FROM ORDERS
  WHERE CUST IN (SELECT CUST_NUM
                 FROM CUSTOMERS
                 WHERE CUST_REP = 102);

/*003*/
CREATE VIEW ORD_BY_REP (WHO, HOW_MANY, TOTAL,
                        LOW, HIGH, AVERAGE)
  AS
  SELECT REP, COUNT(*), SUM(AMOUNT), MIN(AMOUNT),
         MAX(AMOUNT), AVG(AMOUNT)
  FROM ORDERS
  GROUP BY REP;

/*003*/
DROP VIEW EASTREPS CASCADE;

/*004*/
DROP VIEW EASTREPS RESTRICT;