/*001*/
SELECT CITY
FROM OFFICES
WHERE TARGET > (SELECT  SUM(QUOTA)
                FROM SALESREPS
                WHERE REP_OFFICE = OFFICE);

/*002*/
SELECT NAME
FROM SALESREPS
WHERE QUOTA < (.1 * (SELECT SUM(TARGET)
                      FROM OFFICES));

/*003*/
SELECT CITY
FROM OFFICES
WHERE TARGET > (SELECT SUM(QUOTA)
                FROM SALESREPS
                WHERE REP_OFFICE = OFFICE);

/*004*/
/*
=
>
<
<=
>=
<>
*/
SELECT NAME
FROM SALESREPS
WHERE QUOTA >= (SELECT TARGET
                FROM OFFICES
                WHERE CITY = 'Atlanta');

/*005*/
/*
IN
*/
SELECT NAME
FROM SALESREPS
WHERE REP_OFFICE IN (SELECT OFFICE
                     FROM OFFICES
                     WHERE SALES > TARGET);

/*006*/
SELECT COMPANY
FROM CUSTOMERS
WHERE CUST_NUM IN (SELECT DISTINCT CUST
                   FROM ORDERS
                   WHERE MFR = 'ACI'
                    AND PRODUCT LIKE '4100%'
                    AND ORDER_DATE BETWEEN '2017-01-01'
                                   AND '2018-01-01');

/*007*/
SELECT DISTINCT DESCROPTION
FROM PRODUCTS
WHERE EXISTS(SELECT ORDER_NUM
             FROM ORDERS
             WHERE PRODUCT = PRODUCT_ID
              AND MFR = MFR_ID
              AND AMOUNT >= 25000.00);

/*008*/
SELECT COMPANY
FROM CUSTOMERS
WHERE CUST_REP = (SELECT EMPL_NUM
                  FROM SALESREPS
                  WHERE NAME = 'Sue Smith')
  AND NOT EXISTS(SELECT * FROM ORDERS
                 WHERE CUST = CUST_NUM
                 AND AMOUNT > 3000.00);

/*009*/
SELECT NAME
FROM SALESREPS
WHERE (.1 * QUOTA) > ANY (SELECT AMOUNT
                          FROM ORDERS
                          WHERE REP = EMPL_NUM);

/*010*/
SELECT NAME, AGE
FROM SALESREPS
WHERE NOT (EMPL_NUM = ANY (SELECT MGR FROM OFFICES));

/*011*/
/*ALTERNATIVE 010*/
SELECT NAME, AGE
FROM SALESREPS
WHERE NOT EXISTS(SELECT *
                 FROM OFFICES
                 WHERE EMPL_NUM = MGR);

/*012*/
SELECT CITY, TARGET
FROM OFFICES
WHERE (.50 * TARGET) < ALL (SELECT SALES
                            FROM SALESREPS
                            WHERE REP_OFFICE = OFFICE);

/*013*/
SELECT NAME, AGE
FROM SALESREPS
WHERE REP_OFFICE IN (SELECT OFFICE
                     FROM OFFICES
                     WHERE REGION = 'Western');

/*014*/
SELECT COMPANY
FROM CUSTOMERS
WHERE CUST_REP IN (SELECT EMPL_NUM
                   FROM SALESREPS
                   WHERE REP_OFFICE IN (SELECT OFFICE
                                        FROM OFFICES
                                        WHERE REGION = 'Eastern'));

/*015*/
SELECT NAME
FROM SALESREPS MGRS
WHERE AGE > 40
  AND MGRS.EMPL_NUM IN (SELECT MANAGER
                        FROM SALESREPS EMPS
                        WHERE EMPS.SALES > EMPS.QUOTA
                          AND EMPS.REP_OFFICE <> MGRS.REP_OFFICE);

/*016*/
/*HAVING*/
SELECT NAME, AVG(AMOUNT)
FROM SALESREPS, ORDERS
WHERE EMPL_NUM = REP
  AND MFR = 'ACI'
GROUP BY NAME
HAVING AVG(ANOUNT) > (SELECT AVG(AMOUNT)
                      FROM ORDERS);

/*017*/
SELECT NAME, EMPL_NUM, HIRE_DATE, (QUOTA * .9)
FROM SALESREPS
WHERE (REP_OFFICE = 13) OR TITLE = 'VP Sales';

/*018*/
SELECT NAME, CAST(REP_OFFICE AS CHAR), CAST(HIRE_DATE AS CHAR)
FROM SALESREPS;

/*019*/
SELECT PRODUCT, QTY, AMOUNT
FROM OREDERS
WHERE CUST = CAST ('2107' AS INTEGER);

/*020*/
/*CASE*/
SELECT COMPANY,
  CASE WHEN CREDIT_LIMIT > 60000 THEN 'A'
       WHEN CREDIT_LIMIT > 30000 THEN 'B'
       ELSE 'C'
    END AS CREDIT_RATING
FROM CUSTOMERS;

/*021*/
SELECT CITY, SUM(SALESREPS.SALES)
FROM OFFICES, SALESREPS
WHERE OFFICE = CASE WHEN (REP_OFFCIE IS NOT NULL) THEN REP_OFFICE
                    ELSE (SELECT REP_OFFICE
                          FROM SALESREPS MGRS
                          WHERE MGRS.EMPL_NUM = MANAGER)
                    END
GROUP BY CITY;

/*022*/
SELECT NAME, CITY, CASE OFFICE WHEN 11 THEN 'NEW YORK'
                               WHEN 12 THEN 'ILLINOIS'
                               WHEN 13 THEN 'GEORGIA'
                   END AS STATE
FROM OFFICES, SALESREPS
WHERE MGR = EMPL_NUM;

/*023*/
/*COALESCE*/
SELECT NAME, CAOLESCE (QUOTA, SALES, 0.00)
FROM SALESREPS;

/*024*/
/*NULLIF*/
SELECT CITY, SUM(SALESREPS.SALES)
FROM OFFICES, SALESREPS
WHERE OFFICE = NULLIF(REP_OFFICE, 0)
GROUP BY CITY;

/*025*/
SELECT ORDER_NUM, QTY, AMOUNT
FROM REDERS
WHERE (MFR, PRODUCT) = ('ACI', '41002');

/*026*/
SELECT MFR_ID, PRODUCT_ID
FROM PRODUCTS
WHERE PRICE = (SELECT MAX(PRICE)
               FROM PRODUCTS);

/*027*/
SELECT ORDER_NUM, ORDER_DATE
FROM ORDERS
WHERE (MFR, PRODUCT) = (SELECT MFR_ID, PRODUCT_ID
                        FROM PRODUCTS
                        WHERE PRICE = (SELECT MAX(PRICE)
                                       FROM PRODUCTS));

/*028*/
/*BUILD STRINGS*/
INSERT INTO OFFICES (OFFICE, CITY, REGION, MGR, SALES)
    VALUES (23,'','',123,0.00),
           (11,'','',321,0.00),
           (14,'','',231,0.00);

/*029*/
INSERT INTO OFFICES (OFFICE, CITY, REGION, MGR, SALES)
    VALUES (23,'SAN DIEGO','WESTERN',108,0.00),
           (24,'SEATTLE','WESTERN', (SELECT MANAGER
                                     FROM SALESREPS
                                     WHERE EMPL_NUM = 105),0.00);

/*030*/
/*
UNION
INTERSECT
EXCEPT
*/
(SELECT MFR, PRODUCT
FROM ORDERS
WHERE AMOUNT > 30000.00)
UNION
(SELECT MFR_ID, PRODUCT_ID
FROM PRODUCTS
WHERE (PRICE * QTY_ON_HAND) > 30000);

/*031*/
SELECT COMPANY, TOT_ORDERS
FROM CUSTOMERS, (SELECT CUST, SUM(AMOUNT) AS TOT_ORDERS
                 FROM ORDERS
                 GROUP BY CUST)
WHERE (CREDIT_LIMIT > 50000.00)
  AND (CUST_NUM = CUST);


