/*001*/
SELECT CITY
FROM OFFICES
WHERE TARGET > (SELECT  SUM(QUOTA)
                FROM SALESREPS
                WHERE REP_OFFICE = OFFICE);

/*002*/
SELECT NAME
FROM SALESREPS
WHERE QUOTA < (.1 * (SELECT SUM(TARGET)
                      FROM OFFICES));

/*003*/
SELECT CITY
FROM OFFICES
WHERE TARGET > (SELECT SUM(QUOTA)
                FROM SALESREPS
                WHERE REP_OFFICE = OFFICE);

/*004*/
