CREATE TABLE OFFICES (
  OFFICE INTEGER NOT NULL,
  CITY VARCHAR(15) NOT NULL,
  REGION VARCHAR(10) NOT NULL,
  MGR INTEGER,
  TARGET DECIMAL(9,2),
  SALES DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (OFFICE),
  FOREIGN KEY HASMGR (MGR)
  REFERENCES SALESREPS
    ON DELETE SET NULL
);