CREATE TABLE CUSTOMERS (
  CUST_NUM INTEGER NOT NULL,
  COMPANY VARCHAR (20) NOT NULL,
  CUST_REP INTEGER,
  CREDIT_LIMIT DECIMAL(9,2),
  PRIMARY KEY (CUST_NUM),
  FOREIGN KEY HASREP (CUST_REP)
  REFERENCES SALESREPS(EMPL_NUM)
    ON DELETE SET NULL
);