CREATE TABLE ORDERS(
  ORDER_NUM INTEGER NOT NULL,
  ORDER_DATE DATE NOT NULL,
  CUST INTEGER NOT NULL,
  REP INTEGER,
  MFR CHAR(3) NOT NULL,
  PRODUCT CHAR(5) NOT NULL,
  QTY INTEGER NOT NULL,
  AMOUNT DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (ORDER_NUM),
  FOREIGN KEY PLACEDBY (CUST)
  REFERENCES CUSTOMERS (CUST_NUM)
    ON DELETE CASCADE,
  FOREIGN KEY TAKENBY (REP)
  REFERENCES SALESREPS (EMPL_NUM)
    ON DELETE SET NULL,
  FOREIGN KEY ISFOR (MFR, PRODUCT)
  REFERENCES PRODUCTS (MRF_ID, PRODUCT_ID)
    ON DELETE RESTRICT
);