/*001*/
ALTER TABLE CUSTOMERS
    ADD CONTACT_NAME VARCHAR(30);

/*002*/
ALTER TABLE PRODUCTS
    ADD COLUMN MIN_QTY INTEGER NOT NULL DEFAULT 0;

/*003*/
ALTER TABLE SALESREPS
    DROP HIRE_DATE;

/*004*/
ALTER TABLE OFFICES
    ADD CONSTRAINT INREGION
    FOREIGN KEY (REGION)
  REFERENCES REGION;

/*005*/
ALTER TABLE SALESREPS
    DROP CONSTRAINT WORKSIN;

/*006*/
ALTER TABLE OFFICES
    DROP PRIMARY KEY;

