/*001*/
CREATE DOMAIN VALID_OFFICE_ID INTEGER
  CHECK (VALUE BETWEEN 11 AND 99);

CREATE TABLE OFFICES(
  OFFICE VALID_OFFICE_ID NOT NULL,
  CITY VARCHAR(15) NOT NULL,
  REGION VARCHAR(64) NOT NULL DEFAULT 'EASTERN', 
  TARGET DECIMAL(9,2) NOT NULL DEFAULT 0.00,
  SALES DECIMAL(9,2) NOT NULL DEFAULT NULL 
);

/*002*/
CREATE TABLE ORDERS(
  ORDER_NUM INTEGER NOT NULL,
  ORDER_DATE DATE NOT NULL,
  CUST INTEGER NOT NULL,
  REP INTEGER,
  MFR CHAR(3) NOT NULL,
  PRODUCT CHAR(5) NOT NULL,
  QTY INTEGER NOT NULL,
  AMOUNT DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (ORDER_NUM),
  FOREIGN KEY PLACEDBY (CUST)
  REFERENCES CUSTOMERS (CUST_NUM)
    ON DELETE CASCADE,
  FOREIGN KEY TAKENBY (REP)
  REFERENCES SALESREPS (EMPL_NUM)
    ON DELETE SET NULL,
  FOREIGN KEY ISFOR (MFR, PRODUCT)
  REFERENCES PRODUCTS (MRF_ID, PRODUCT_ID)
    ON DELETE RESTRICT
);

/*003*/
CREATE TABLE OFFICES (
  OFFICE INTEGER NOT NULL,
  CITY VARCHAR(15) NOT NULL,
  REGION VARCHAR(10) NOT NULL,
  MGR INTEGER,
  TARGET DECIMAL(9,2),
  SALES DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (OFFICE),
  FOREIGN KEY HASMGR (MGR)
  REFERENCES SALESREPS(EMPL_NUM)
    ON DELETE SET NULL,
    UNIQUE (CITY)
);

/*004*/
CREATE TABLE OFFICES (
  OFFICE INTEGER NOT NULL,
  CITY VARCHAR(15) NOT NULL,
  REGION VARCHAR(10) NOT NULL,
  MGR INTEGER,
  TARGET DECIMAL(9,2),
  SALES DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (OFFICE),
  FOREIGN KEY HASMGR (MGR)
  REFERENCES SALESREPS(EMPL_NUM)
    ON DELETE SET NULL,
    CHECK (TARGET >= 0.00)
);

/*005*/
CREATE TABLE SALESREPS(
  EMPL_NUM INTEGER NOT NULL,
  NAME VARCHAR(15) NOT NULL,
  AGE INTEGER,
  REP_OFFICE INTEGER,
  TITLE VARCHAR(10),
  HIRE_DATE DATE NOT NULL,
  MANAGER INTEGER,
  QUOTA DECIMAL(9,2),
  SALES DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (EMPL_NUM),
  FOREIGN KEY (MANAGER)
  REFERENCES SALESREPS (EMPL_NUM)
    ON DELETE SET NULL,
  FOREIGN KEY WORKSIN (REP_OFFICE)
  REFERENCES OFFICES (OFFICE)
    ON DELETE SET NULL,
  CONSTRAINT QUOTA_CAP CHECK ((HIRE_DATE < '2017-01-01') OR
                              (QUOTA <= 300000))
);

/*006*/
CREATE TABLE OFFICES (
  ID INTEGER NOT NULL 
) WITH LOCATION = (SEC1,SEC2,SEC3);

/*007*/
CREATE DATABASE NAME
  ON DEVICE1, DEVICE2, DEVICE3
  
/*008*/
CREATE TABLE OFFICES(
  /*FIELD*/
) ON SEGMET SEG1A;

