/*001*/
CREATE SCHEMA JSCHEMA AUTHORIZATION PAVEL
  CREATE TABLE PEOPLE(
    NAME VARCHAR(64),
    AGE INTEGER
  )
  CREATE TABLE PLACES(
    CITY VARCHAR(30),
    STATE VARCHAR(30)
  )
  GRANT ALL PRIVILEGES
    ON PEOPLE
    TO PUBLIC
  GRANT SELECT
    ON PLACES
    TO MARY;

/*002*/
DROP SCHEMA JSCHEMA CASCADE;

