/*001*/
SELECT DEFINER, TABNAME
FROM SYSCAT.TABLES
  WHERE TYPE = 'T';

/*002*/
SELECT TABSCHEME, TABNAME, COLNAME
FROM SYSCAT.COLUMNS
  WHERE TYPESCHEME = 'SYSIBM'
  AND TYPENAME = 'DATE';

/*003*/
COMMENT ON TABLE OFFICES
  IS 'COMMENT FOR TABLE';

/*004*/
SELECT CONSTNAME, REFTABNAME, TABNAME,
FROM SYSCAT.REFERENCES
  WHERE DEFINER = USER;

/*005*/
SELECT USERNAME
FROM DBA_USERS;

/*006*/
SELECT TABLE_NAME
FROM TABLES;